// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkuybturazislquqaxci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrdXlidHVyYXppc2xxdXFheGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODQ5MzEsImV4cCI6MjA2OTQ2MDkzMX0.4E1C0WggIhJN9U1dAgaNbDQK8BePfVxAQxJLxUrVKX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});